name: 'Dependabot Automerge - Action'

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

permissions:
  pull-requests: write
  issues: write
  contents: read
  checks: write

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v1.7.1
        with:
          ignoreActions: worker,WIP
          checkInterval: 60 #300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Automerge'
        id: automerge
        uses: pascalgn/automerge-action@v0.15.5
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_LABELS: 'dependencies'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_DELETE_BRANCH: true

      - name: feedback
        if: steps.automerge.outputs.mergeResult == 'merged'
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
