name: 'Dependabot Automerge - Action'

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: WyriHaximus/github-action-wait-for-status@v2
        with:
          ignoreActions: worker,WIP
          checkInterval: 60 #300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Automerge'
        id: automerge
        uses: pascalgn/automerge-action@v0.15.3
        if: steps.waitforstatuschecks.outputs.status == 'success'
        env:
          MERGE_LABELS: 'dependencies'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_DELETE_BRANCH: true
